rauc/meta-rauc-community

meta-rauc-raspberrypi/recipes-bsp/rpi-u-boot-scr/rpi-u-boot-scr.bbappend

To my surprise `FILESEXTRAPATHS` was leaking custom `boot.cmd.in` anyway. Tested with rpi4, now it's working as expected.

rpi-u-boot-scr.bbappend: fixed conditional include of boot.cmd.in.

---

meta-rauc-raspberrypi/recipes-bsp/rpi-u-boot-scr/rpi-u-boot-scr.bbappend

Signed-off-by: Bartłomiej Burdukiewicz <bartlomiej.burdukiewicz@gmail.com>

rpi-u-boot-scr.bbappend: fixed override typo.

---

meta-rauc-sunxi/recipes-core/bundles/update-bundle.bb
meta-rauc-sunxi/recipes-core/rauc/files/system.conf

A small bit of cleanup. 
Realized that the `RAUC_BUNDLE_COMPATIBLE` and system.conf `compatible` values were different which was causing apparent compatibility issues when there were none. At the very least, they need to be consistent and probably should be something different than "OrangePi" since this compatibility should, in theory, work for more sunxi devices. 
Also changed RAUC_SLOT_rootfs to `core-image-minimal` which is likely what it should be as its default.

Sunxi - Clean up compatibility inconsistency 

---

meta-rauc-qemux86/conf/layer.conf

I have verified the "meta-rauc-qemux86" layer works with with the poky "hardknott" branch.

qemux86: Confirmed layer is SERIES_COMPAT with hardknott

---

meta-rauc-qemux86/conf/layer.conf
meta-rauc-qemux86/recipes-bsp/boot-image/boot-image.bb

* Add 'kirkstone' to `LAYERSERIES_COMPAT`
* Fix [cleandirs] handling for boot-image recipe
Fixes #31

Update meta-rauc-qemux86 for 'kirkstone'

---

README.rst

This should make it easier to find the Matrix channel.

README.rst: add badges for license and matrix chat channel

---

meta-rauc-qemux86/README.rst
meta-rauc-qemux86/recipes-core/bundles/qemu-demo-bundle.bb
meta-rauc-qemux86/recipes-core/images/core-image-minimal.bbappend
meta-rauc-qemux86/recipes-core/rauc/files/qemux86-64/system.conf
meta-rauc-qemux86/wic/qemux86-grub-efi.wks

This adds configuration required to test RAUC's 1.8 [adaptive update](https://rauc.readthedocs.io/en/latest/advanced.html#adaptive-updates) feature on qemux86-64.
To enable it, just uncomment the two lines in the `qemu-demo-bundle.bb` file and upload it to a web server you have access to from your qemu.

Prepare meta-rauc-qemux86 for RAUC Adaptive Updates

---

meta-rauc-raspberrypi/recipes-core/rauc/files/system.conf
meta-rauc-raspberrypi/wic/sdimage-dual-raspberrypi.wks.in

Add a data directory with a fixed size of 100MB for Raspberry Pi and configure data-directory to /data/ in RAUC's system.conf.
This makes use of the new 'data-directory' introduced by RAUC version 1.8 which will be used for adaptive updates and other new features in future.
Signed-off-by: Leon Anavi <leon.anavi@konsulko.com>

meta-rauc-raspberrypi: Add data directory

---

meta-rauc-qemux86/README.rst

Added note explaining how to forward ports from the QEMU system to the host system when using Slirp.

qemux86: README.rst: Add port forwarding note

---

meta-rauc-tegra/recipes-core/bundles/update-bundle.bb

The kernel configuration already enabled 'verity' support, but the bundle did not.
The 'verity' format is the successor of the legacy 'plain' format which is still supported by RAUC but should not be used for new projects.
Also note that only the 'verity' format allows using RAUC features as streaming, encryption and adaptive updates.
Signed-off-by: Enrico Jorns <ejo@pengutronix.de>

meta-rauc-tegra: switch to using 'verity' bundle format

---

meta-rauc-qemux86/conf/layer.conf

honister is EOL and since the version of meta-rauc-qemux86 requires RAUC 1.8 which is not part of meta-rauc's honister branch, compatibility is clearly broken.
Same applies to 'hardknott'.
Signed-off-by: Enrico Jorns <ejo@pengutronix.de>

qemux86: layer.conf: remove compatiblity with 'honister' and 'hardknott'

---

meta-rauc-nxp/recipes-bsp/u-boot/u-boot-fslc_%.bbappend

Since commit a3d3c2d to poky and given that the LAYERSERIES_COMPAT for
meta-rauc-nxp is kirkstone, UBOOT_ENV_SUFFIX and UBOOT_ENV can be used
to run the uboot-mkimage command from
poky/meta/recipes-bsp/u-boot/u-boot.inc

Remove the appended do_install

---

meta-rauc-raspberrypi/conf/layer.conf

Adds `mickledore` compatibility.

raspberrypi: Add mickledore compatibility

---

meta-rauc-raspberrypi/recipes-core/base-files/base-files_%.bbappend

The data partition from the core image fails mount due to missing mount point. Solution copied from meta-rauc-qemux86

raspberrypi: Update base-files_%.bbappend

---

.github/workflows/meta-rauc-qemux86.yml
.github/workflows/meta-rauc-raspberrypi.yml
meta-rauc-qemux86/conf/layer.conf
meta-rauc-raspberrypi/conf/layer.conf

Adds minimal workflows capable of setting up and parsing a valid layer and configuration combination.
This should at least prevent running into obvious issues or incompatibilities with the respective release branch.
The builds trigger only for changes to the respective layer directory.
Updated the layer compatibilities to let the workflow trigger (and to fix master builds).

Add Minimal Github Action Workflows For qemux86 and raspberrypi

---

meta-rauc-qemux86/recipes-core/rauc/files/qemux86-64/system.conf

For demonstration purpose, this configures the RAUC event logging framework, introduced with RAUC v1.11, to handle two log files: one with a readable installation history, and another with a json-parsable history.

qemux86: rauc: system.conf: define example rauc history logger

---

meta-rauc-qemux86/recipes-core/images/core-image-minimal.bbappend

This avoids some non-determinism in the resulting image, reducing the download size for adaptive RAUC updates.
Also fix the comment about 'inode size' which is actually 'bytes-per-inode' from the original oe-core setting of `EXTRA_IMAGECMD`.

qemux86: core-image-minimal: use fixed directory hash seed

---

meta-rauc-raspberrypi/conf/layer.conf
meta-rauc-raspberrypi/recipes-core/rauc/files/rauc-grow-data-partition.service
meta-rauc-raspberrypi/recipes-core/rauc/rauc-conf.bbappend
meta-rauc-raspberrypi/recipes-core/rauc/rauc_%.bbappend

With the current service, only the extended partition is expanded to fill the space. This also extends partition 6 which is the current /home and the last partition on the disk.

rpi: Auto grow the actual /home partition.

---

meta-rauc-beaglebone/conf/layer.conf
meta-rauc-beaglebone/recipes-bsp/u-boot/files/0001-am335x_evm_defconfig-rauc.patch
meta-rauc-beaglebone/recipes-core/rauc/rauc-conf.bbappend
meta-rauc-beaglebone/recipes-core/rauc/rauc_%.bbappend

Changes to support the Yocto Project release Scarthgap and drop support of previous releases because of changes in U-Boot version and in meta-rauc.

BeagleBone Black: Support Scarthgap

---

meta-rauc-raspberrypi/conf/layer.conf

Align LAYERSERIES_COMPAT with meta-rauc as of the moment to support Yocto releases Nanbield and Scarthgap.

meta-rauc-raspberrypi: Nanbield and Scarthgap

---

create-example-keys.sh
meta-rauc-raspberrypi/conf/layer.conf
meta-rauc-raspberrypi/recipes-core/bundles/update-bundle.bb

1. Enable the u-boot support provided by v2024.04 via the meta-lts-mixins 'scarthgap/u-boot' branch.
2. Fix the `create-example-keys.sh` script to use `openssl-native` built by openembedded instead of relying on host version compatibility.
3. Relax the variable settings in meta-rauc-raspberrypi `update-bundle.bb` for the keys to allow the autogenerated `site.conf` variables from the `create-example-keys.sh` to be functional. This allows the developer to have their own local keys and not rely on the vulnerable, publicly disclosed private keys in the layer.

scarthgap/raspberrypi5 u-boot and example certs generation

---

meta-rauc-raspberrypi/README.rst

Add instructions how to move the Linux kernel to the rootfs on Raspberry Pi and to update with a RAUC bundle #12

meta-rauc-raspberrypi/README.rst: Kernel update

---

meta-rauc-raspberrypi/README.rst

Raspberry Pi 5 U-Boot support is added in v2024.04.
This version is provided by `meta-lts-mixins` branch `scarthgap/u-boot`.

meta-rauc-raspberrypi: README.rst: Add Raspberry Pi 5 dependency

---

meta-rauc-raspberrypi/recipes-core/rauc/rauc-conf.bbappend
meta-rauc-raspberrypi/recipes-core/rauc/rauc_%.bbappend

This GitHub pull request adapts to the oe-core rework to enforce a separate directory for unpacking local sources (UNPACKDIR) instead of directly using WORKDIR.
Follows the preliminary guideline from:
https://lists.openembedded.org/g/openembedded-architecture/message/2007

Raspberry Pi: WORKDIR -> UNPACKDIR transition

---

meta-rauc-raspberrypi/README.rst
meta-rauc-raspberrypi/recipes-bsp/rpi-u-boot-scr/files/boot.cmd.in
meta-rauc-raspberrypi/recipes-core/images/core-image-minimal.bbappend

I have successfully done a kernel update using a RAUC update bundle on Raspberry Pi 5 with these patches and the instructions from the README.rst.

Make Kernel A/B updates (as part of rootfs) default behavior for meta-rauc-raspberrypi

---

meta-rauc-qemux86/conf/layer.conf
meta-rauc-qemux86/recipes-bsp/grub/rauc-qemu-grubconf.bb

This reverts two commits that were not intended for `scarthgap` but ended up before the `scarthgap` branch point.

qemux86: fix compatibility with `scarthgap`

---

README.rst
meta-rauc-raspberrypi/README.rst

This GitHub pull request contains the following minor fixes in the documentation:
* `README.rst`: Replace PI with Pi in Raspberry Pi.
* `meta-rauc-raspberrypi/README.rst`: Fix links. Thanks to Gerd Kautzmann for reporting the dead links.

Documentation Fixes

---

meta-rauc-raspberrypi/README.rst
meta-rauc-raspberrypi/recipes-bsp/rpi-u-boot-scr/files/boot.cmd.in
meta-rauc-raspberrypi/recipes-core/images/core-image-minimal.bbappend

Essentially the same patches as in #102.
I tested them on the scarthgap branch as well, so they should be added there as well.

Make Kernel A/B updates (as part of rootfs) default behavior for meta-rauc-raspberrypi (scarthgap)

---

.github/workflows/meta-rauc-qemux86.yml
.github/workflows/meta-rauc-raspberrypi.yml

For 'scarthgap' we need to check against 'scarthgap' instead of 'master'.

Pin CI Jobs to 'scarthgap'

---

meta-rauc-qemux86/README.rst
meta-rauc-qemux86/kas-qemu-grub.yml

Just some minor fixes for the kas file..

qemux86: update and enhance kas file

---

meta-rauc-sunxi/README.rst
meta-rauc-sunxi/recipes-bsp/u-boot/files/0005-configs-Merrii_A80_Optimus_defconfig-RAUC.patch
meta-rauc-sunxi/recipes-bsp/u-boot/u-boot_%.bbappend

Add support for Merrii A80 Optimus board with Allwinner 80 SoC from the sun9i family.

meta-rauc-sunxi: Add Merrii A80 Optimus

---

meta-rauc-sunxi/README.rst
meta-rauc-sunxi/recipes-bsp/u-boot/files/0006-Add-support-for-Cubieboard-4-board-with-Allwinner-80.patch
meta-rauc-sunxi/recipes-bsp/u-boot/u-boot_%.bbappend

Add support for Cubieboard4 board with Allwinner 80 SoC from the sun9i family.
Signed-off-by:  Lazar Hristov <lhristov@gmail.com>

Add Cubieboard4 A80

---

.github/workflows/generate.py
.github/workflows/meta-rauc-qemux86.yml

We want to build more layers in CI while avoiding too much redundancy in the workflow definitions. Although this could be done using reusable workflows or custom actions, templating them using jinja is much simpler and more flexible.
To avoid conflicts with the GitHub Actions syntax, we use « and » instead of { and }.
The only change to the existing workflows is the order in which 'bitbake-layers add-layer' is run.

.github/workflows: generate workflows from template

---

meta-rauc-raspberrypi/recipes-core/images/core-image-minimal.bbappend

Use RPI_EXTRA_IMAGE_BOOT_FILES to remove the kernel from the /boot partition because it is in rootfs.

core-image-minimal.bbappend: Remove kernel

---

meta-rauc-raspberrypi/recipes-core/images/core-image-minimal.bbappend

Use RPI_EXTRA_IMAGE_BOOT_FILES to remove the kernel from the /boot partition because it is in rootfs.
Reported-by: Andrey Ezhkov <andrey.ezhkov@konsulko.com>

Scarthgap: Raspberry Pi: core-image-minimal.bbappend: Remove kernel

---

meta-rauc-st-stm32mp/recipes-core/udev/files/rauc.rules

The enumeration of storage sometimes may change to mmcblk1. Add mmcblk1p10 and mmcblk1p11 to ignore list to avoid mounting the A and the B partitions when udev-extraconf is included in the image.
Follow-up fix for #150.

meta-rauc-st-stm32mp: rauc.rules: mmcblk1

---

.github/workflows/meta-rauc-qemux86.yml
.github/workflows/meta-rauc-raspberrypi.yml

Since walnascar, the minimum required bitbake version will be 3.9.0:
> RuntimeError: Sorry, python 3.9.0 or later is required for this version of bitbake
This will allow continuing to run the GitHub actions on the GH-hosted runners.
Also, explicitly install 'chrpath', which does not seem to be part of the default installation anymore.

.github/workflows: run on ubuntu 22.04 for python > 3.8.x

---

meta-rauc-qemuarm/conf/layer.conf
meta-rauc-qemuarm/kas-qemuarm.yml
meta-rauc-qemuarm/recipes-bsp/u-boot/u-boot_%.bbappend

Add support for `walnascar` poky release, for both `qemuarm64` and `qemuarm` machines.
Supposedly also fixes a minor bug for the u-boot script for `qemuarm`.

qemuarm: Default to walnascar release

---

.github/workflows/generate.py

The result matches to repository contents again.
Fixes: 6613e7fc25a6 (".github/workflows: run on ubuntu 22.04 for python > 3.8.x")

.github/workflows: update generator for ubuntu-22.04

---

meta-rauc-raspberrypi/recipes-bsp/u-boot/files/rpi_arm64_defconfig.patch

This failed as u-boot version changed in meta-lts-mixins https://git.yoctoproject.org/meta-lts-mixins/commit/?h=scarthgap/u-boot&id=68856926465b56b98599ab2506fceb0d1bcfad5b

recipes-bsp/u-boot/files/rpi_arm64_defconfig.patch: re-align path

---

meta-rauc-qemuarm/conf/layer.conf
meta-rauc-qemuarm/recipes-bsp/u-boot/files/boot.cmd.in
meta-rauc-qemuarm/recipes-bsp/u-boot/u-boot_%.bbappend
meta-rauc-qemuarm/recipes-core/images/core-image-minimal.bbappend
meta-rauc-qemuarm/recipes-kernel/linux/devicetree-qemuarm_1.0.bb
meta-rauc-qemuarm/recipes-kernel/linux/linux-yocto_%.bbappend

Instead of patching the kernel source tree, the `devicetree.bbclass` provides a clean way to provide out-of-tree device trees. Hence, this PR implements the canonical solution and introduces a dedicated `devicetree-qemuarm` package for the static device tree dumped from QEMU.
Besides, some parts of the code are simplified.
This is a follow-up of the initial PR series to add support for the `qemuarm` and `qemuarm64` machines.

meta-rauc-qemuarm: Canonical solution for devicetree
